name: Test

on: push

jobs:
  test:
    name: Run library tests
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v3
      - name: Use .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Run unit tests
        uses: cake-build/cake-action@v1
        with:
          target: Test
