name: Test

on: pull_request, push

jobs:
  test:
    name: Run library tests
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Run unit tests
        uses: cake-build/cake-action@v1
        with:
          target: Test
